// Generated by Wrangler on Sat Aug 24 2024 03:44:50 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
  DB: D1Database;
  VECTORIZE: VectorizeIndex;
  AI: AI;
  ENVIRONMENT: string;
}
